version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    steps:
      - checkout
      # start proprietary DB using private Docker image
      # with credentials stored in the UI
    
      # deploy the image
      - run:
          command: docker run -p 80:80 zodinx/zozo:latest
          no_output_timeout: 7h